stages:
  - install
  - test
  - build

default:
  image: node:22
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

install:
  stage: install
  script:
    - npm ci

test:
  stage: test
  script:
    - npm run test:ci
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - coverage/

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
