stages:
  - install
  - test
  - build

default:
  image: node:22
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

install:
  stage: install
  script:
    - npm ci

test:
  stage: test
  image: node:20
  script:
    - npm ci
    - npm run test:coverage
  artifacts:
    when: always
    paths:
      - coverage/
    reports:
      coverage_report:
        coverage_format: lcov
        path: coverage/lcov.info

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
